server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

  security:
    user:
      name: admin
      password: admin123

jwt:
  secret: test-secret-key
  expiration-ms: 86400000